/* ddsClient.c
   Generated by gSOAP 2.7.9 from DigiDocService.h
   Copyright(C) 2000-2006, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "ddsH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) ddsClient.c ver 2.7.9 2007-03-12 16:55:20 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_d__StartSession(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *SigningProfile, char *SigDocXML, bool bHoldSession, struct d__DataFileData *datafile, struct d__StartSessionResponse *result)
{	struct d__StartSession soap_tmp_d__StartSession;
	if (!soap_endpoint)
		soap_endpoint = "http://www.sk.ee:8095/DigiDocService";
	soap->encodingStyle = "";
	soap_tmp_d__StartSession.SigningProfile = SigningProfile;
	soap_tmp_d__StartSession.SigDocXML = SigDocXML;
	soap_tmp_d__StartSession.bHoldSession = bHoldSession;
	soap_tmp_d__StartSession.datafile = datafile;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_d__StartSession(soap, &soap_tmp_d__StartSession);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_d__StartSession(soap, &soap_tmp_d__StartSession, "d:StartSession", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_d__StartSession(soap, &soap_tmp_d__StartSession, "d:StartSession", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_d__StartSessionResponse(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_d__StartSessionResponse(soap, result, "d:StartSessionResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_d__CloseSession(struct soap *soap, const char *soap_endpoint, const char *soap_action, long Sesscode, struct d__CloseSessionResponse *result)
{	struct d__CloseSession soap_tmp_d__CloseSession;
	if (!soap_endpoint)
		soap_endpoint = "http://www.sk.ee:8095/DigiDocService";
	soap->encodingStyle = "";
	soap_tmp_d__CloseSession.Sesscode = Sesscode;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_d__CloseSession(soap, &soap_tmp_d__CloseSession);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_d__CloseSession(soap, &soap_tmp_d__CloseSession, "d:CloseSession", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_d__CloseSession(soap, &soap_tmp_d__CloseSession, "d:CloseSession", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_d__CloseSessionResponse(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_d__CloseSessionResponse(soap, result, "d:CloseSessionResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_d__CreateSignedDoc(struct soap *soap, const char *soap_endpoint, const char *soap_action, long Sesscode, char *Format, char *Version, struct d__CreateSignedDocResponse *result)
{	struct d__CreateSignedDoc soap_tmp_d__CreateSignedDoc;
	if (!soap_endpoint)
		soap_endpoint = "http://www.sk.ee:8095/DigiDocService";
	soap->encodingStyle = "";
	soap_tmp_d__CreateSignedDoc.Sesscode = Sesscode;
	soap_tmp_d__CreateSignedDoc.Format = Format;
	soap_tmp_d__CreateSignedDoc.Version = Version;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_d__CreateSignedDoc(soap, &soap_tmp_d__CreateSignedDoc);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_d__CreateSignedDoc(soap, &soap_tmp_d__CreateSignedDoc, "d:CreateSignedDoc", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_d__CreateSignedDoc(soap, &soap_tmp_d__CreateSignedDoc, "d:CreateSignedDoc", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_d__CreateSignedDocResponse(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_d__CreateSignedDocResponse(soap, result, "d:CreateSignedDocResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_d__AddDataFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, long Sesscode, char *FileName, char *MimeType, char *ContentType, long Size, char *DigestType, char *DigestValue, char *Content, struct d__AddDataFileResponse *result)
{	struct d__AddDataFile soap_tmp_d__AddDataFile;
	if (!soap_endpoint)
		soap_endpoint = "http://www.sk.ee:8095/DigiDocService";
	soap->encodingStyle = "";
	soap_tmp_d__AddDataFile.Sesscode = Sesscode;
	soap_tmp_d__AddDataFile.FileName = FileName;
	soap_tmp_d__AddDataFile.MimeType = MimeType;
	soap_tmp_d__AddDataFile.ContentType = ContentType;
	soap_tmp_d__AddDataFile.Size = Size;
	soap_tmp_d__AddDataFile.DigestType = DigestType;
	soap_tmp_d__AddDataFile.DigestValue = DigestValue;
	soap_tmp_d__AddDataFile.Content = Content;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_d__AddDataFile(soap, &soap_tmp_d__AddDataFile);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_d__AddDataFile(soap, &soap_tmp_d__AddDataFile, "d:AddDataFile", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_d__AddDataFile(soap, &soap_tmp_d__AddDataFile, "d:AddDataFile", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_d__AddDataFileResponse(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_d__AddDataFileResponse(soap, result, "d:AddDataFileResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_d__RemoveDataFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, long Sesscode, char *DataFileId, struct d__RemoveDataFileResponse *result)
{	struct d__RemoveDataFile soap_tmp_d__RemoveDataFile;
	if (!soap_endpoint)
		soap_endpoint = "http://www.sk.ee:8095/DigiDocService";
	soap->encodingStyle = "";
	soap_tmp_d__RemoveDataFile.Sesscode = Sesscode;
	soap_tmp_d__RemoveDataFile.DataFileId = DataFileId;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_d__RemoveDataFile(soap, &soap_tmp_d__RemoveDataFile);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_d__RemoveDataFile(soap, &soap_tmp_d__RemoveDataFile, "d:RemoveDataFile", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_d__RemoveDataFile(soap, &soap_tmp_d__RemoveDataFile, "d:RemoveDataFile", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_d__RemoveDataFileResponse(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_d__RemoveDataFileResponse(soap, result, "d:RemoveDataFileResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_d__GetSignedDoc(struct soap *soap, const char *soap_endpoint, const char *soap_action, long Sesscode, struct d__GetSignedDocResponse *result)
{	struct d__GetSignedDoc soap_tmp_d__GetSignedDoc;
	if (!soap_endpoint)
		soap_endpoint = "http://www.sk.ee:8095/DigiDocService";
	soap->encodingStyle = "";
	soap_tmp_d__GetSignedDoc.Sesscode = Sesscode;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_d__GetSignedDoc(soap, &soap_tmp_d__GetSignedDoc);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_d__GetSignedDoc(soap, &soap_tmp_d__GetSignedDoc, "d:GetSignedDoc", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_d__GetSignedDoc(soap, &soap_tmp_d__GetSignedDoc, "d:GetSignedDoc", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_d__GetSignedDocResponse(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_d__GetSignedDocResponse(soap, result, "d:GetSignedDocResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_d__GetSignedDocInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, long Sesscode, struct d__GetSignedDocInfoResponse *result)
{	struct d__GetSignedDocInfo soap_tmp_d__GetSignedDocInfo;
	if (!soap_endpoint)
		soap_endpoint = "http://www.sk.ee:8095/DigiDocService";
	soap->encodingStyle = "";
	soap_tmp_d__GetSignedDocInfo.Sesscode = Sesscode;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_d__GetSignedDocInfo(soap, &soap_tmp_d__GetSignedDocInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_d__GetSignedDocInfo(soap, &soap_tmp_d__GetSignedDocInfo, "d:GetSignedDocInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_d__GetSignedDocInfo(soap, &soap_tmp_d__GetSignedDocInfo, "d:GetSignedDocInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_d__GetSignedDocInfoResponse(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_d__GetSignedDocInfoResponse(soap, result, "d:GetSignedDocInfoResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_d__GetDataFile(struct soap *soap, const char *soap_endpoint, const char *soap_action, long Sesscode, char *DataFileId, struct d__GetDataFileResponse *result)
{	struct d__GetDataFile soap_tmp_d__GetDataFile;
	if (!soap_endpoint)
		soap_endpoint = "http://www.sk.ee:8095/DigiDocService";
	soap->encodingStyle = "";
	soap_tmp_d__GetDataFile.Sesscode = Sesscode;
	soap_tmp_d__GetDataFile.DataFileId = DataFileId;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_d__GetDataFile(soap, &soap_tmp_d__GetDataFile);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_d__GetDataFile(soap, &soap_tmp_d__GetDataFile, "d:GetDataFile", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_d__GetDataFile(soap, &soap_tmp_d__GetDataFile, "d:GetDataFile", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_d__GetDataFileResponse(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_d__GetDataFileResponse(soap, result, "d:GetDataFileResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_d__GetSignersCertificate(struct soap *soap, const char *soap_endpoint, const char *soap_action, long Sesscode, char *SignatureId, struct d__GetSignersCertificateResponse *result)
{	struct d__GetSignersCertificate soap_tmp_d__GetSignersCertificate;
	if (!soap_endpoint)
		soap_endpoint = "http://www.sk.ee:8095/DigiDocService";
	soap->encodingStyle = "";
	soap_tmp_d__GetSignersCertificate.Sesscode = Sesscode;
	soap_tmp_d__GetSignersCertificate.SignatureId = SignatureId;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_d__GetSignersCertificate(soap, &soap_tmp_d__GetSignersCertificate);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_d__GetSignersCertificate(soap, &soap_tmp_d__GetSignersCertificate, "d:GetSignersCertificate", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_d__GetSignersCertificate(soap, &soap_tmp_d__GetSignersCertificate, "d:GetSignersCertificate", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_d__GetSignersCertificateResponse(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_d__GetSignersCertificateResponse(soap, result, "d:GetSignersCertificateResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_d__GetNotarysCertificate(struct soap *soap, const char *soap_endpoint, const char *soap_action, long Sesscode, char *SignatureId, struct d__GetNotarysCertificateResponse *result)
{	struct d__GetNotarysCertificate soap_tmp_d__GetNotarysCertificate;
	if (!soap_endpoint)
		soap_endpoint = "http://www.sk.ee:8095/DigiDocService";
	soap->encodingStyle = "";
	soap_tmp_d__GetNotarysCertificate.Sesscode = Sesscode;
	soap_tmp_d__GetNotarysCertificate.SignatureId = SignatureId;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_d__GetNotarysCertificate(soap, &soap_tmp_d__GetNotarysCertificate);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_d__GetNotarysCertificate(soap, &soap_tmp_d__GetNotarysCertificate, "d:GetNotarysCertificate", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_d__GetNotarysCertificate(soap, &soap_tmp_d__GetNotarysCertificate, "d:GetNotarysCertificate", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_d__GetNotarysCertificateResponse(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_d__GetNotarysCertificateResponse(soap, result, "d:GetNotarysCertificateResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_d__GetNotary(struct soap *soap, const char *soap_endpoint, const char *soap_action, long Sesscode, char *SignatureId, struct d__GetNotaryResponse *result)
{	struct d__GetNotary soap_tmp_d__GetNotary;
	if (!soap_endpoint)
		soap_endpoint = "http://www.sk.ee:8095/DigiDocService";
	soap->encodingStyle = "";
	soap_tmp_d__GetNotary.Sesscode = Sesscode;
	soap_tmp_d__GetNotary.SignatureId = SignatureId;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_d__GetNotary(soap, &soap_tmp_d__GetNotary);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_d__GetNotary(soap, &soap_tmp_d__GetNotary, "d:GetNotary", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_d__GetNotary(soap, &soap_tmp_d__GetNotary, "d:GetNotary", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_d__GetNotaryResponse(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_d__GetNotaryResponse(soap, result, "d:GetNotaryResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_d__GetTSACertificate(struct soap *soap, const char *soap_endpoint, const char *soap_action, long Sesscode, char *TimestampId, struct d__GetTSACertificateResponse *result)
{	struct d__GetTSACertificate soap_tmp_d__GetTSACertificate;
	if (!soap_endpoint)
		soap_endpoint = "http://www.sk.ee:8095/DigiDocService";
	soap->encodingStyle = "";
	soap_tmp_d__GetTSACertificate.Sesscode = Sesscode;
	soap_tmp_d__GetTSACertificate.TimestampId = TimestampId;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_d__GetTSACertificate(soap, &soap_tmp_d__GetTSACertificate);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_d__GetTSACertificate(soap, &soap_tmp_d__GetTSACertificate, "d:GetTSACertificate", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_d__GetTSACertificate(soap, &soap_tmp_d__GetTSACertificate, "d:GetTSACertificate", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_d__GetTSACertificateResponse(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_d__GetTSACertificateResponse(soap, result, "d:GetTSACertificateResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_d__GetTimestamp(struct soap *soap, const char *soap_endpoint, const char *soap_action, long Sesscode, char *TimestampId, struct d__GetTimestampResponse *result)
{	struct d__GetTimestamp soap_tmp_d__GetTimestamp;
	if (!soap_endpoint)
		soap_endpoint = "http://www.sk.ee:8095/DigiDocService";
	soap->encodingStyle = "";
	soap_tmp_d__GetTimestamp.Sesscode = Sesscode;
	soap_tmp_d__GetTimestamp.TimestampId = TimestampId;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_d__GetTimestamp(soap, &soap_tmp_d__GetTimestamp);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_d__GetTimestamp(soap, &soap_tmp_d__GetTimestamp, "d:GetTimestamp", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_d__GetTimestamp(soap, &soap_tmp_d__GetTimestamp, "d:GetTimestamp", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_d__GetTimestampResponse(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_d__GetTimestampResponse(soap, result, "d:GetTimestampResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_d__GetCRL(struct soap *soap, const char *soap_endpoint, const char *soap_action, long Sesscode, char *SignatureId, struct d__GetCRLResponse *result)
{	struct d__GetCRL soap_tmp_d__GetCRL;
	if (!soap_endpoint)
		soap_endpoint = "http://www.sk.ee:8095/DigiDocService";
	soap->encodingStyle = "";
	soap_tmp_d__GetCRL.Sesscode = Sesscode;
	soap_tmp_d__GetCRL.SignatureId = SignatureId;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_d__GetCRL(soap, &soap_tmp_d__GetCRL);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_d__GetCRL(soap, &soap_tmp_d__GetCRL, "d:GetCRL", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_d__GetCRL(soap, &soap_tmp_d__GetCRL, "d:GetCRL", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_d__GetCRLResponse(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_d__GetCRLResponse(soap, result, "d:GetCRLResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_d__GetSignatureModules(struct soap *soap, const char *soap_endpoint, const char *soap_action, long Sesscode, char *Platform, char *Phase, char *Type, struct d__GetSignatureModulesResponse *result)
{	struct d__GetSignatureModules soap_tmp_d__GetSignatureModules;
	if (!soap_endpoint)
		soap_endpoint = "http://www.sk.ee:8095/DigiDocService";
	soap->encodingStyle = "";
	soap_tmp_d__GetSignatureModules.Sesscode = Sesscode;
	soap_tmp_d__GetSignatureModules.Platform = Platform;
	soap_tmp_d__GetSignatureModules.Phase = Phase;
	soap_tmp_d__GetSignatureModules.Type = Type;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_d__GetSignatureModules(soap, &soap_tmp_d__GetSignatureModules);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_d__GetSignatureModules(soap, &soap_tmp_d__GetSignatureModules, "d:GetSignatureModules", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_d__GetSignatureModules(soap, &soap_tmp_d__GetSignatureModules, "d:GetSignatureModules", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_d__GetSignatureModulesResponse(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_d__GetSignatureModulesResponse(soap, result, "d:GetSignatureModulesResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_d__PrepareSignature(struct soap *soap, const char *soap_endpoint, const char *soap_action, long Sesscode, char *SignersCertificate, char *SignersTokenId, char *Role, char *City, char *State, char *PostalCode, char *Country, char *SigningProfile, struct d__PrepareSignatureResponse *result)
{	struct d__PrepareSignature soap_tmp_d__PrepareSignature;
	if (!soap_endpoint)
		soap_endpoint = "http://www.sk.ee:8095/DigiDocService";
	soap->encodingStyle = "";
	soap_tmp_d__PrepareSignature.Sesscode = Sesscode;
	soap_tmp_d__PrepareSignature.SignersCertificate = SignersCertificate;
	soap_tmp_d__PrepareSignature.SignersTokenId = SignersTokenId;
	soap_tmp_d__PrepareSignature.Role = Role;
	soap_tmp_d__PrepareSignature.City = City;
	soap_tmp_d__PrepareSignature.State = State;
	soap_tmp_d__PrepareSignature.PostalCode = PostalCode;
	soap_tmp_d__PrepareSignature.Country = Country;
	soap_tmp_d__PrepareSignature.SigningProfile = SigningProfile;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_d__PrepareSignature(soap, &soap_tmp_d__PrepareSignature);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_d__PrepareSignature(soap, &soap_tmp_d__PrepareSignature, "d:PrepareSignature", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_d__PrepareSignature(soap, &soap_tmp_d__PrepareSignature, "d:PrepareSignature", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_d__PrepareSignatureResponse(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_d__PrepareSignatureResponse(soap, result, "d:PrepareSignatureResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_d__FinalizeSignature(struct soap *soap, const char *soap_endpoint, const char *soap_action, long Sesscode, char *SignatureId, char *SignatureValue, struct d__FinalizeSignatureResponse *result)
{	struct d__FinalizeSignature soap_tmp_d__FinalizeSignature;
	if (!soap_endpoint)
		soap_endpoint = "http://www.sk.ee:8095/DigiDocService";
	soap->encodingStyle = "";
	soap_tmp_d__FinalizeSignature.Sesscode = Sesscode;
	soap_tmp_d__FinalizeSignature.SignatureId = SignatureId;
	soap_tmp_d__FinalizeSignature.SignatureValue = SignatureValue;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_d__FinalizeSignature(soap, &soap_tmp_d__FinalizeSignature);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_d__FinalizeSignature(soap, &soap_tmp_d__FinalizeSignature, "d:FinalizeSignature", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_d__FinalizeSignature(soap, &soap_tmp_d__FinalizeSignature, "d:FinalizeSignature", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_d__FinalizeSignatureResponse(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_d__FinalizeSignatureResponse(soap, result, "d:FinalizeSignatureResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_d__RemoveSignature(struct soap *soap, const char *soap_endpoint, const char *soap_action, long Sesscode, char *SignatureId, struct d__RemoveSignatureResponse *result)
{	struct d__RemoveSignature soap_tmp_d__RemoveSignature;
	if (!soap_endpoint)
		soap_endpoint = "http://www.sk.ee:8095/DigiDocService";
	soap->encodingStyle = "";
	soap_tmp_d__RemoveSignature.Sesscode = Sesscode;
	soap_tmp_d__RemoveSignature.SignatureId = SignatureId;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_d__RemoveSignature(soap, &soap_tmp_d__RemoveSignature);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_d__RemoveSignature(soap, &soap_tmp_d__RemoveSignature, "d:RemoveSignature", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_d__RemoveSignature(soap, &soap_tmp_d__RemoveSignature, "d:RemoveSignature", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_d__RemoveSignatureResponse(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_d__RemoveSignatureResponse(soap, result, "d:RemoveSignatureResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_d__GetVersion(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct d__GetVersionResponse *result)
{	struct d__GetVersion soap_tmp_d__GetVersion;
	if (!soap_endpoint)
		soap_endpoint = "http://www.sk.ee:8095/DigiDocService";
	soap->encodingStyle = "";
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_d__GetVersion(soap, &soap_tmp_d__GetVersion);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_d__GetVersion(soap, &soap_tmp_d__GetVersion, "d:GetVersion", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_d__GetVersion(soap, &soap_tmp_d__GetVersion, "d:GetVersion", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_d__GetVersionResponse(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_d__GetVersionResponse(soap, result, "d:GetVersionResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_d__MobileSign(struct soap *soap, const char *soap_endpoint, const char *soap_action, long Sesscode, char *SignerIDCode, char *SignersCountry, char *SignerPhoneNo, char *ServiceName, char *AdditionalDataToBeDisplayed, char *Language, char *Role, char *City, char *StateOrProvince, char *PostalCode, char *CountryName, char *SigningProfile, char *MessagingMode, long AsyncConfiguration, bool ReturnDocInfo, bool ReturnDocData, struct d__MobileSignResponse *result)
{	struct d__MobileSign soap_tmp_d__MobileSign;
	if (!soap_endpoint)
		soap_endpoint = "http://www.sk.ee:8095/DigiDocService";
	soap->encodingStyle = "";
	soap_tmp_d__MobileSign.Sesscode = Sesscode;
	soap_tmp_d__MobileSign.SignerIDCode = SignerIDCode;
	soap_tmp_d__MobileSign.SignersCountry = SignersCountry;
	soap_tmp_d__MobileSign.SignerPhoneNo = SignerPhoneNo;
	soap_tmp_d__MobileSign.ServiceName = ServiceName;
	soap_tmp_d__MobileSign.AdditionalDataToBeDisplayed = AdditionalDataToBeDisplayed;
	soap_tmp_d__MobileSign.Language = Language;
	soap_tmp_d__MobileSign.Role = Role;
	soap_tmp_d__MobileSign.City = City;
	soap_tmp_d__MobileSign.StateOrProvince = StateOrProvince;
	soap_tmp_d__MobileSign.PostalCode = PostalCode;
	soap_tmp_d__MobileSign.CountryName = CountryName;
	soap_tmp_d__MobileSign.SigningProfile = SigningProfile;
	soap_tmp_d__MobileSign.MessagingMode = MessagingMode;
	soap_tmp_d__MobileSign.AsyncConfiguration = AsyncConfiguration;
	soap_tmp_d__MobileSign.ReturnDocInfo = ReturnDocInfo;
	soap_tmp_d__MobileSign.ReturnDocData = ReturnDocData;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_d__MobileSign(soap, &soap_tmp_d__MobileSign);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_d__MobileSign(soap, &soap_tmp_d__MobileSign, "d:MobileSign", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_d__MobileSign(soap, &soap_tmp_d__MobileSign, "d:MobileSign", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_d__MobileSignResponse(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_d__MobileSignResponse(soap, result, "d:MobileSignResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_d__GetStatusInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, long Sesscode, bool ReturnDocInfo, bool WaitSignature, struct d__GetStatusInfoResponse *result)
{	struct d__GetStatusInfo soap_tmp_d__GetStatusInfo;
	if (!soap_endpoint)
		soap_endpoint = "http://www.sk.ee:8095/DigiDocService";
	soap->encodingStyle = "";
	soap_tmp_d__GetStatusInfo.Sesscode = Sesscode;
	soap_tmp_d__GetStatusInfo.ReturnDocInfo = ReturnDocInfo;
	soap_tmp_d__GetStatusInfo.WaitSignature = WaitSignature;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_d__GetStatusInfo(soap, &soap_tmp_d__GetStatusInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_d__GetStatusInfo(soap, &soap_tmp_d__GetStatusInfo, "d:GetStatusInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_d__GetStatusInfo(soap, &soap_tmp_d__GetStatusInfo, "d:GetStatusInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_d__GetStatusInfoResponse(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_d__GetStatusInfoResponse(soap, result, "d:GetStatusInfoResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_d__MobileAuthenticate(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *IDCode, char *CountryCode, char *PhoneNo, char *Language, char *ServiceName, char *MessageToDisplay, char *SPChallenge, char *MessagingMode, long AsyncConfiguration, bool ReturnCertData, bool ReturnRevocationData, struct d__MobileAuthenticateResponse *result)
{	struct d__MobileAuthenticate soap_tmp_d__MobileAuthenticate;
	if (!soap_endpoint)
		soap_endpoint = "http://www.sk.ee:8095/DigiDocService";
	soap->encodingStyle = "";
	soap_tmp_d__MobileAuthenticate.IDCode = IDCode;
	soap_tmp_d__MobileAuthenticate.CountryCode = CountryCode;
	soap_tmp_d__MobileAuthenticate.PhoneNo = PhoneNo;
	soap_tmp_d__MobileAuthenticate.Language = Language;
	soap_tmp_d__MobileAuthenticate.ServiceName = ServiceName;
	soap_tmp_d__MobileAuthenticate.MessageToDisplay = MessageToDisplay;
	soap_tmp_d__MobileAuthenticate.SPChallenge = SPChallenge;
	soap_tmp_d__MobileAuthenticate.MessagingMode = MessagingMode;
	soap_tmp_d__MobileAuthenticate.AsyncConfiguration = AsyncConfiguration;
	soap_tmp_d__MobileAuthenticate.ReturnCertData = ReturnCertData;
	soap_tmp_d__MobileAuthenticate.ReturnRevocationData = ReturnRevocationData;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_d__MobileAuthenticate(soap, &soap_tmp_d__MobileAuthenticate);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_d__MobileAuthenticate(soap, &soap_tmp_d__MobileAuthenticate, "d:MobileAuthenticate", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_d__MobileAuthenticate(soap, &soap_tmp_d__MobileAuthenticate, "d:MobileAuthenticate", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_d__MobileAuthenticateResponse(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_d__MobileAuthenticateResponse(soap, result, "d:MobileAuthenticateResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_d__GetMobileAuthenticateStatus(struct soap *soap, const char *soap_endpoint, const char *soap_action, long Sesscode, bool WaitSignature, struct d__GetMobileAuthenticateStatusResponse *result)
{	struct d__GetMobileAuthenticateStatus soap_tmp_d__GetMobileAuthenticateStatus;
	if (!soap_endpoint)
		soap_endpoint = "http://www.sk.ee:8095/DigiDocService";
	soap->encodingStyle = "";
	soap_tmp_d__GetMobileAuthenticateStatus.Sesscode = Sesscode;
	soap_tmp_d__GetMobileAuthenticateStatus.WaitSignature = WaitSignature;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_d__GetMobileAuthenticateStatus(soap, &soap_tmp_d__GetMobileAuthenticateStatus);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_d__GetMobileAuthenticateStatus(soap, &soap_tmp_d__GetMobileAuthenticateStatus, "d:GetMobileAuthenticateStatus", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_d__GetMobileAuthenticateStatus(soap, &soap_tmp_d__GetMobileAuthenticateStatus, "d:GetMobileAuthenticateStatus", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_d__GetMobileAuthenticateStatusResponse(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_d__GetMobileAuthenticateStatusResponse(soap, result, "d:GetMobileAuthenticateStatusResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_d__MobileCreateSignature(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *IDCode, char *SignersCountry, char *PhoneNo, char *Language, char *ServiceName, char *MessageToDisplay, char *Role, char *City, char *StateOrProvince, char *PostalCode, char *CountryName, char *SigningProfile, struct d__DataFileDigestList *DataFiles, char *Format, char *Version, char *SignatureID, char *MessagingMode, long AsyncConfiguration, struct d__MobileCreateSignatureResponse *result)
{	struct d__MobileCreateSignature soap_tmp_d__MobileCreateSignature;
	if (!soap_endpoint)
		soap_endpoint = "http://www.sk.ee:8095/DigiDocService";
	soap->encodingStyle = "";
	soap_tmp_d__MobileCreateSignature.IDCode = IDCode;
	soap_tmp_d__MobileCreateSignature.SignersCountry = SignersCountry;
	soap_tmp_d__MobileCreateSignature.PhoneNo = PhoneNo;
	soap_tmp_d__MobileCreateSignature.Language = Language;
	soap_tmp_d__MobileCreateSignature.ServiceName = ServiceName;
	soap_tmp_d__MobileCreateSignature.MessageToDisplay = MessageToDisplay;
	soap_tmp_d__MobileCreateSignature.Role = Role;
	soap_tmp_d__MobileCreateSignature.City = City;
	soap_tmp_d__MobileCreateSignature.StateOrProvince = StateOrProvince;
	soap_tmp_d__MobileCreateSignature.PostalCode = PostalCode;
	soap_tmp_d__MobileCreateSignature.CountryName = CountryName;
	soap_tmp_d__MobileCreateSignature.SigningProfile = SigningProfile;
	soap_tmp_d__MobileCreateSignature.DataFiles = DataFiles;
	soap_tmp_d__MobileCreateSignature.Format = Format;
	soap_tmp_d__MobileCreateSignature.Version = Version;
	soap_tmp_d__MobileCreateSignature.SignatureID = SignatureID;
	soap_tmp_d__MobileCreateSignature.MessagingMode = MessagingMode;
	soap_tmp_d__MobileCreateSignature.AsyncConfiguration = AsyncConfiguration;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_d__MobileCreateSignature(soap, &soap_tmp_d__MobileCreateSignature);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_d__MobileCreateSignature(soap, &soap_tmp_d__MobileCreateSignature, "d:MobileCreateSignature", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_d__MobileCreateSignature(soap, &soap_tmp_d__MobileCreateSignature, "d:MobileCreateSignature", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_d__MobileCreateSignatureResponse(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_d__MobileCreateSignatureResponse(soap, result, "d:MobileCreateSignatureResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_d__GetMobileCreateSignatureStatus(struct soap *soap, const char *soap_endpoint, const char *soap_action, long Sesscode, bool WaitSignature, struct d__GetMobileCreateSignatureStatusResponse *result)
{	struct d__GetMobileCreateSignatureStatus soap_tmp_d__GetMobileCreateSignatureStatus;
	if (!soap_endpoint)
		soap_endpoint = "http://www.sk.ee:8095/DigiDocService";
	soap->encodingStyle = "";
	soap_tmp_d__GetMobileCreateSignatureStatus.Sesscode = Sesscode;
	soap_tmp_d__GetMobileCreateSignatureStatus.WaitSignature = WaitSignature;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_d__GetMobileCreateSignatureStatus(soap, &soap_tmp_d__GetMobileCreateSignatureStatus);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_d__GetMobileCreateSignatureStatus(soap, &soap_tmp_d__GetMobileCreateSignatureStatus, "d:GetMobileCreateSignatureStatus", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_d__GetMobileCreateSignatureStatus(soap, &soap_tmp_d__GetMobileCreateSignatureStatus, "d:GetMobileCreateSignatureStatus", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_d__GetMobileCreateSignatureStatusResponse(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_d__GetMobileCreateSignatureStatusResponse(soap, result, "d:GetMobileCreateSignatureStatusResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_mss__MSS_USCORESignatureDummy(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct mss_DummyResp *resp)
{	struct mss__MSS_USCORESignatureDummy soap_tmp_mss__MSS_USCORESignatureDummy;
	if (!soap_endpoint)
		soap_endpoint = "http://www.sk.ee:8096/MSSP_GW";
	soap->encodingStyle = NULL;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_mss__MSS_USCORESignatureDummy(soap, &soap_tmp_mss__MSS_USCORESignatureDummy);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_mss__MSS_USCORESignatureDummy(soap, &soap_tmp_mss__MSS_USCORESignatureDummy, "mss:MSS_SignatureDummy", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_mss__MSS_USCORESignatureDummy(soap, &soap_tmp_mss__MSS_USCORESignatureDummy, "mss:MSS_SignatureDummy", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	soap_default_mss_DummyResp(soap, resp);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_mss_DummyResp(soap, resp, "mss-DummyResp", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

/* End of ddsClient.c */
