.TH qdigidocclient "1" "July 2011"
.SH NAME
qdigidocclient \- an application for digitally signing and encrypting
documents
.SH SYNOPSIS
.TP
\fPqdigidocclient\fP
.SH DESCRIPTION
QDigiDoc is an application for digitally signing and encrypting
documents in BDoc, DDoc, and CDoc container formats. These file
formats are widespread in Estonia where they are used for storing
legally binding digital signatures.

.PP
For more information about the qdigidocclient and for full
documentation, visit
https://code.google.com/p/esteid/wiki/QDigiDocHelp

.SH AUTHORS
.B qdigidocclient
was written by Jargo Kõster <jargo@innovaatik.ee> and Raul Metsma
<raul@innovaatik.ee>

.SH "SEE ALSO"
.BR qesteidutil (1),
.BR qdigidoccrypto (1),
.BR cdigidoc (1),
