.TH qesteidutil "1" "July 2011" 
.SH NAME
qesteidutil \- an application for managing Estonian ID Card
.SH SYNOPSIS
.TP
\fPqesteidutil\fP
.SH DESCRIPTION
QEsteidUtil is an application for managing Estonian ID Card. In an
user-friendly interface it is possible to change and unlock PINs,
examine detailed information about personal data file on the card,
extract and view certificates, set up mobile ID, and configure
@eesti.ee email.

.PP
For more information about the qesteidutil and for full documentation,
visit https://code.google.com/p/esteid/wiki/QEsteidUtilHelp

.SH AUTHORS
.B qesteidutil
was written by Jargo Kõster <jargo@innovaatik.ee>, Raul Metsma
<raul@innovaatik.ee> and Kalev Lember <kalev@smartlink.ee>

.SH "SEE ALSO"
.BR qdigidocclient (1),
.BR qdigidoccrypto (1),
.BR cdigidoc (1),