#!/usr/bin/env bash

PKMKPIDFORAPP="$1/Contents/Resources/pkmkpidforapp"
PKMKSENDAE="$1/Contents/Resources/pkmksendae"

# Quit Safari
RESULT=`"$PKMKPIDFORAPP" 'com.apple.safari' 'Safari'`
if [ $RESULT -gt 0 ]; then
	RESULT=`"$PKMKSENDAE" $RESULT 'quit'`
fi

# Delete the old Safari plugin
echo 'Removing Safari plug-in'
rm -rf /Library/Internet\ Plug-Ins/EstEIDWP.plugin

exit 0