#!/usr/bin/env bash

PKMKPIDFORAPP="$1/Contents/Resources/pkmkpidforapp"
PKMKSENDAE="$1/Contents/Resources/pkmksendae"

# Quit Safari
RESULT=`"$PKMKPIDFORAPP" 'org.mozilla.firefox' 'Firefox'`
if [ $RESULT -gt 0 ]; then
	RESULT=`"$PKMKSENDAE" $RESULT 'quit'`
fi

exit 0