#!/bin/sh
#
# $Id$
#
# Check for proper OS version for the package (meant to be used by the
# MacPorts port which replaces 9 with the version of Darwin
# needed).

base_version=`uname -r | sed 's/\..*//'`
if [[ ${base_version} != 9 ]]; then
   # This maps to message 16 in InstallationCheck.strings (Apple allows
   # 16-31 for custom messages); that message should also be customized
   # like this script
   exit 112
fi
exit 0

