#!/usr/bin/env bash

# Configure automatic software updates
/Applications/Utilities/EstEIDSU.app/Contents/Resources/agent --launchd enable /Library/LaunchAgents/org.esteid.updater.plist

# Install certificates
for f in /usr/local/share/libdigidoc/certs/*.{crt,pem}
do
	if test -f "$f"; then
		/usr/bin/security import "$f" -k /System/Library/Keychains/SystemCACertificates.keychain
		/usr/bin/security import "$f" -k /System/Library/Keychains/SystemRootCertificates.keychain
	fi
done

/usr/bin/security add-trusted-cert -d -k /System/Library/Keychains/SystemRootCertificates.keychain /usr/local/share/libdigidoc/certs/JUUR-SK.crt

# Clear tokend cache
rm -rf /var/db/TokenCache/tokens/*

# Launch Keychain Utility
v=`/usr/bin/sw_vers -productVersion | cut -f 1-2 -d "."`

if test "$v" = "10.5"; then
	/usr/bin/open -a "/Applications/Utilities/EstEIDSU.app/Contents/Resources/Keychain Tool.app"
fi

# Remove obsolete openoffice extension
if [ -f /usr/local/share/ooo-digidoc.oxt ]; then
   unopkg=/Applications/OpenOffice.org.app/Contents/program/unopkg
   if $unopkg list --shared ee.smartlink.ooo.digidoc >/dev/null 2>&1; then
       $unopkg remove --shared ee.smartlink.ooo.digidoc >/dev/null 2>&1
       $unopkg list --shared >/dev/null 2>&1
   fi
   rm -rf /Library/Receipts/org.esteid.installer.openoffice*
   rm -f /usr/local/share/ooo-digidoc.oxt
fi

exit 0
