# - Find OOo SDK
# Find OOSDK includes and executable
#
#  OOSDK_INCLUDE_DIR - Where to find OOSDK include sub-directory.
#  OOSDK_EXECUTABLE  - OOSDK compiler.
#  OOSDK_FOUND       - True if OOSDK found.


IF (CPPUMAKER)
  # Already in cache, be silent.
  SET(CPPUMAKER_FIND_QUIETLY TRUE)
ENDIF (CPPUMAKER)

FIND_PROGRAM(CPPUMAKER NAMES cppumaker PATHS "${OO_SDK_HOME}/bin")
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CppuMaker DEFAULT_MSG CPPUMAKER)
MARK_AS_ADVANCED(CPPUMAKER)


IF (OOSDK_INCLUDE_DIR)
  # Already in cache, be silent.
  SET(OOSDK_FIND_QUIETLY TRUE)
ENDIF (OOSDK_INCLUDE_DIR)

message( STATUS "searching libraries in ${OO_SDK_URE_LIB_DIR} ${OO_SDK_HOME_LIB_DIR}")

if (APPLE)
  set(ENV_LIB_VAR DYLD_LIBRARY_PATH)
else (APPLE)
  set(ENV_LIB_VAR LD_LIBRARY_PATH)
endif (APPLE)

SET(CPPU_NAMES icppu uno_cppu cppu libuno_cppu)
FIND_LIBRARY(CPPU_LIBRARY NAMES ${CPPU_NAMES} PATHS ${OO_SDK_URE_LIB_DIR} ${OO_SDK_HOME_LIB_DIR} ENV ${ENV_LIB_VAR})

SET(CPPUHELPER_NAMES uno_cppuhelpergcc3 icppuhelper cppuhelper libuno_cppuhelpergcc3)
FIND_LIBRARY(CPPUHELPER_LIBRARY NAMES ${CPPUHELPER_NAMES} PATHS ${OO_SDK_URE_LIB_DIR} ${OO_SDK_HOME_LIB_DIR} ENV ${ENV_LIB_VAR})

SET(SAL_NAMES isal uno_sal sal libuno_sal)
FIND_LIBRARY(SAL_LIBRARY NAMES ${SAL_NAMES} PATHS ${OO_SDK_URE_LIB_DIR} ${OO_SDK_HOME_LIB_DIR} ENV ${ENV_LIB_VAR})

SET(SALHELPER_NAMES isalhelper uno_salhelpergcc3 salhelper libuno_salhelpergcc3)
FIND_LIBRARY(SALHELPER_LIBRARY NAMES ${SALHELPER_NAMES} PATHS ${OO_SDK_URE_LIB_DIR} ${OO_SDK_HOME_LIB_DIR} ENV ${ENV_LIB_VAR})

SET(STLPORT_NAMES istlport_vc71 stlport_gcc stlport_vc71 stlport libstlport_gcc)
FIND_LIBRARY(STLPORT_LIBRARY NAMES ${STLPORT_NAMES} PATHS ${OO_SDK_URE_LIB_DIR} ${OO_SDK_HOME_LIB_DIR} ENV ${ENV_LIB_VAR})

# Handle the QUIETLY and REQUIRED arguments and set STLPORT_FOUND to
# TRUE if all listed variables are TRUE.
FIND_PACKAGE_HANDLE_STANDARD_ARGS(STLPort DEFAULT_MSG STLPORT_LIBRARY)

IF(STLPORT_FOUND)
  SET( OOSDK_LIBRARIES ${OOSDK_LIBRARIES} ${STLPORT_LIBRARY})
ENDIF(STLPORT_FOUND)

# Handle the QUIETLY and REQUIRED arguments and set OOSDK_FOUND to
# TRUE if all listed variables are TRUE.
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OOSDK DEFAULT_MSG OOSDK_LIBRARY OOSDK_INCLUDE_DIR)

IF(OOSDK_FOUND)
  SET( OOSDK_LIBRARIES ${OOSDK_LIBRARIES} ${CPPU_LIBRARY} ${CPPUHELPER_LIBRARY} ${SAL_LIBRARY} ${SALHELPER_LIBRARY})
ELSE(OOSDK_FOUND)
  SET( OOSDK_LIBRARIES )
ENDIF(OOSDK_FOUND)

MARK_AS_ADVANCED(OOSDK_LIBRARY OOSDK_INCLUDE_DIR)
