package ee.itp.dds.service;

public enum ResponseStatus {
  
  OK,
  ERROR,
  INPUT_DATA_ERROR,
  WRONG_SESSION_CODE,
  CANT_CREATE_NEW_SESSION,
  SIGNATURE_MODULE_WRONG_PLANFORM,
  SIGNATURE_MODULE_WRONG_PHASE,
  SIGNATURE_MODULE_WRONG_TYPE, 
  WRONG_SIGNATURE_ID, NO_SIGNATURE_ID, 
  CANT_READ_NOTARYS_CERT, 
  CANT_READ_SIGNER_CERT

}
